version: '3.7'
services:
    proxy:
        image: traefik:v2.5
        ports:
            - 80:80
            # - 443:443
            - 8080:8080
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            # - "--entrypoints.websecure.address=:443"
            # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            # - "--certificatesresolvers.kawfeeresolver.acme.httpchallenge=true"
            # - "--certificatesresolvers.kawfeeresolver.acme.httpchallenge.entrypoint=web"
            # - "--certificatesresolvers.kawfeeresolver.acme.email=cyclodaddy@gmail.com"
            # - "--certificatesresolvers.kawfeeresolver.acme.storage=/letsencrypt/acme.json"
        volumes:
            - "proxy:/letsencrypt:rw"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        depends_on: 
            - "jekyll"
        networks:
            - "jekyll"
    wet:
        image: nginx:alpine
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.wet.loadbalancer.server.port=80"
            - "traefik.http.routers.wet.rule=PathPrefix(`/themes-dist`)"
            - "traefik.http.routers.wet.entrypoints=web"
            # - "traefik.http.routers.wet.entrypoints=websecure"
            # - "traefik.http.routers.wet.tls.certresolver=kawfeeresolver"
            - "traefik.http.routers.wet.service=wet"
        volumes:
            - "/home/debian/src/wet/themes-dist:/usr/share/nginx/html/themes-dist"
        networks:
            - "jekyll"
    jekyll:
        image: jekyll/jekyll:4
        command: jekyll serve 0.0.0.0
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.jekyll.loadbalancer.server.port=4000"
            - "traefik.http.routers.jekyll.rule=PathPrefix(`/`)"
            - "traefik.http.routers.jekyll.entrypoints=web"
            # - "traefik.http.routers.jekyll.entrypoints=websecure"
            # - "traefik.http.routers.jekyll.tls.certresolver=kawfeeresolver"
            - "traefik.http.routers.jekyll.service=jekyll"
        volumes:
            - "/home/debian/src/jekyll:/srv/jekyll"
        networks:
            - "jekyll"
    rally:
        image: opencadc/phoenix:slim-node-10
        command: mix phx.server
        working_dir: "/app"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.rally.loadbalancer.server.port=4004"
            - "traefik.http.routers.rally.rule=PathPrefix(`/rally`)"
            - "traefik.http.routers.rally.entrypoints=web"
            # - "traefik.http.routers.rally.entrypoints=websecure"
            # - "traefik.http.routers.rally.tls.certresolver=kawfeeresolver"
            - "traefik.http.routers.rally.service=rally"
        volumes:
            - "/home/debian/src/rally:/app"
        networks:
            - "jekyll"
        environment: 
            PORT: 4004

    meetings:
        image: opencadc/phoenix:slim-node-10
        command: mix phx.server
        working_dir: /app
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.meetings.loadbalancer.server.port=4300"
            - "traefik.http.routers.meetings.rule=PathPrefix(`/meetings`)"
            - "traefik.http.routers.meetings.entrypoints=web"
            # - "traefik.http.routers.rally.entrypoints=websecure"
            # - "traefik.http.routers.rally.tls.certresolver=kawfeeresolver"
            - "traefik.http.routers.rallmeetingsy.service=meetings"
        volumes:
            - "/home/debian/src/moriarty:/app"
        networks:
            - "jekyll"
        environment: 
            PORT: 4300

networks:
    jekyll:
        external: true

volumes:
    proxy:
        external: true
